# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:04
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='вес')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Category')),
            ],
            options={
                'verbose_name_plural': 'категории товаров',
                'verbose_name': 'категория товара',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='цена')),
                ('image', models.ImageField(upload_to='goods', verbose_name='изображение товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Category')),
            ],
            options={
                'verbose_name_plural': 'товары',
                'verbose_name': 'товар',
            },
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StoreBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='если оставить пустым - сгенерируется автоматически', populate_from=models.CharField(max_length=100, verbose_name='название'), verbose_name='адрес страницы')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='логотип')),
                ('website', models.URLField(blank=True, null=True, verbose_name='адрес сайта')),
                ('description', ckeditor.fields.RichTextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_category_id', models.PositiveIntegerField(verbose_name='id категории в системе магазина')),
                ('store_category_title', models.PositiveIntegerField(verbose_name='название категории в системе магазина')),
                ('our_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Category', verbose_name='категория на сайте')),
                ('store_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreBrand')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название торговой точки')),
                ('address', models.TextField(verbose_name='адрес')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('store_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreBrand', verbose_name='название магазина')),
            ],
        ),
        migrations.AddField(
            model_name='storeadmin',
            name='store_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreBrand', verbose_name='название магазина'),
        ),
        migrations.AddField(
            model_name='storeadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.StoreBrand', verbose_name='магазин'),
        ),
    ]
